metadata:
  kind: codefresh
  installer:
    # type: 
    #   "operator" - apply codefresh crd definition
    #   "helm" - install/upgrade helm chart from client
    type: operator
    operator:
      #dockerRegistry: gcr.io/codefresh-enterprise
      #image: codefresh/cf-onprem-operator
      #imageTag: 
      #serviceAccountName:
      #skipCRD:
    helm:
      chart: codefresh 
      repoUrl: http://charts.codefresh.io/prod
      #version:

kubernetes:
  namespace: codefresh
  #context: 
  #kubeconfig:

global:
  ### Codefresh App domain name. appUrl is manadatory parameter
  appUrl: 
  appProtocol: https
  
  # stepsCatalogOnPremise: true
  # stepsCatalogOnPremiseRegistry: <your_registry_url>

tls:
  selfSigned: true
  cert: certs/ssl.crt
  key: certs/private.key

images:
  codefreshRegistrySa: sa.json
  # usePrivateRegistry: false
  # privateRegistry:
  #   address:
  #   username:
  #   password:
  lists:
  - images/images-list

dbinfra:
  enabled: false
  #storageClass: 

### Firebase secret - set if you use Firebase for log streaming
firebaseSecret: 

