apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: default scc for Codefresh Runner
  name: codefresh-runner-default
priority: 5
users:
- system:serviceaccount:codefresh-runner:admin
- system:serviceaccount:codefresh-runner:runner
- system:serviceaccount:codefresh-runner:volume-provisioner-runner
groups: []
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: null
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- local
- nfs
- persistentVolumeClaim
- projected
- secret