metadata:
  kind: helmChart
  installer:
    type: helm
    helm:
      chart: external-nodes
      release: cf-external-nodes

kubernetes:
  namespace: codefresh
  #context: 
  #kubeconfig:

nodeRegistarJob:
  backoffLimit: 10
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 3600
  dockerRegistry:
  image: codefresh/cli
  imageTag: latest

cf-api-token: 
consul:
  address: cf-consul
  port: 8500

## Set runtime environments
runtimeEnvironments:
  - name: default-nodes
    extends: system/default
    cluster: codefresh
    protocol: http
    #alternateLoggerConf: external-nodes
    nodes:
    - address: 
      # name: node1
      # port: 2376
    # - address:
      # name:
      # port:

alternateLoggerConf:
  external-nodes:
    mongoUri: 
    redisUri: