apiVersion: v1
kind: Service
metadata:
  name: cf-redis
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.redis.name }}

spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    component: codefresh-redis
  type: ClusterIP