apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.namePrefix}}cfapi
spec:
  host: {{ .Values.host }}
  path: /api
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: cf-cfapi
    weight: 100
  # wildcardPolicy: None