{{- if .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: cf-onprem-operator-registry
  labels:
    app: cf-onprem-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson .Values.dockerconfigjson | b64enc | quote }} 
{{- end }}