apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-onprem-operator
  labels:
    app: cf-onprem-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cf-onprem-operator
  template:
    metadata:
      labels:
        name: cf-onprem-operator
        app: cf-onprem-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "cf-onprem-operator" }}
      {{- if .Values.dockerconfigjson }}
      imagePullSecrets:
        - name: cf-onprem-operator-registry
      {{- end }}
      containers:
        - name: cf-onprem-operator
          image: "{{ .Values.dockerRegistry | default "docker.io"}}/{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cf-onprem-operator"
