{{- if not .Values.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-onprem-operator
  labels:
    app: cf-onprem-operator
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
{{- end }}
