{{ if not .Values.serviceAccountName }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cf-onprem-operator
  labels:
    app: cf-onprem-operator  
subjects:
- kind: ServiceAccount
  name: cf-onprem-operator
roleRef:
  kind: Role
  name: cf-onprem-operator
  apiGroup: rbac.authorization.k8s.io
{{ end }}
