apiVersion: batch/v1
kind: Job
metadata:
  name: cf-node-registar
spec:
  backoffLimit: {{ .Values.nodeRegistarJob.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.nodeRegistarJob.activeDeadlineSeconds }}
  # ttlSecondsAfterFinished: {{ .Values.nodeRegistarJob.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: register
        image: "{{ .Values.nodeRegistarJob.dockerRegistry | default "docker.io" }}/{{ .Values.nodeRegistarJob.image }}:{{ .Values.nodeRegistarJob.imageTag | default "latest" }}"
        command:
          - bash
          - -c
          - |
            BASE_DIR=/tmp/codefresh
            mkdir -pv ${BASE_DIR}
            cp -rLv /opt/mounts/* ${BASE_DIR}/
            chmod +x ${BASE_DIR}/scripts/*.sh
            ${BASE_DIR}/scripts/register-all-nodes.sh
            ${BASE_DIR}/scripts/deploy-all-re.sh
            # sleep 3600
        volumeMounts:
        - name: scripts
          mountPath: /opt/mounts/scripts
        - name: nodes-config
          mountPath: /opt/mounts/nodes
        - name: runtime-environments-config
          mountPath: /opt/mounts/runtime-environments
      volumes:
      - name: scripts
        configMap:
          name: cf-node-registar-scripts
      - name: nodes-config
        configMap:
          name: cf-node-registar-nodes
      - name: runtime-environments-config
        configMap:
          name: cf-node-registar-runtime-environments
