metadata:
  kind: helmChart
  installer:
    type: helm
    helm:
      chart: external-nodes
      release: cf-external-nodes

kubernetes:
  namespace: codefresh-dev
  #context: 
  #kubeconfig:

nodeRegistarJob:
  dockerRegistry: artifactory.six-group.net
  image: codefresh/cli
  imageTag: latest

cf-api-token: 
consul: http://cf-consul:8500

## Set runtime environments
runtimeEnvironments:
  - name: default-nodes
    extends: system/default
    cluster: codefresh
    protocol: http
    #alternateLoggerConf: external-nodes
    nodes:
    - address: mdzhlbmac07.standard.six-group.net
      name: test-node-1
      port: 4243
    # - address:
      # name:
      # port:

alternateLoggerConf:
  external-nodes:
    mongoUri: 
    redisUri: