metadata:
  kind: backup-manager
  installer:
    type: helm
    helm:
      chart: cf-backup-manager
      release: cf-backup-manager

kubernetes:
  namespace: codefresh
  #context: 
  #kubeconfig:

storage:
  longTerm:
    accessMode: "ReadWriteOnce"
    storageClass: "standard"
    size: 10Gi
  tmp:
    accessMode: "ReadWriteOnce"
    storageClass: "standard" 
    size: 3Gi
        
jobConfigs:
  cfBackupPlan:
    target:
      # set the value mongo URI only if you need to override the value
      # otherwise leave it blank for the installer to get it automatically
      uri: ""
    scheduler:
      cron: "0 */6 * * *"
      retention: 28
      timeout: 60
